### ISSUE TITLE
merge-with being passed seq of lazy-seqs

### ISSUE THREAD

**Issue by mfikes** [clj-commons/secretary#100]
There is a potential change in flight for ClojureScript to make `merge-with` consistent with Clojure. In particular the use of `first` and `second` in the implementation would be changed with `key` and `value`. https://dev.clojure.org/jira/browse/CLJS-2943

This line https://github.com/gf3/secretary/blob/1f2036a694e49f58a97c9401878602148f9d6310/src/secretary/core.cljs#L252 passes a seq of lazy seqs (each of length 2) to `merge-with`. The `conj` function, when applied to a map, will accept a seq of map entries, and with this change, `merge-with` would be revised to reflect this behavior, causing an issue with passing a seq of seqs.

**Comment by mfikes** [comment]
The patch in https://dev.clojure.org/jira/browse/CLJS-2943 has landed on ClojureScript master.

**Comment by rsslldnphy** [comment]
Can confirm this has broken secretary for me with the latest Clojurescript. Submitted a fix in #101.

**Comment by borkdude** [comment]
There’s also a fix in #94

**Comment by rsslldnphy** [comment]
Ah great! Didn't see that. Well whichever gets merged - the main thing is that secretary carries on working 😄 .

**Comment by gf3** [comment]
sorry, i don't have time to maintain this project anymore. sadly i don't get to use clojure much anymore. anyone interested in becoming a maintainer?

**Comment by gf3** [comment]
> @gf3 There is an effort to start a home for done/retired/orphaned cli-projects over at [http://github.com/clj-commons](https://github.com/clj-commons). I'm sure we could give secretary a nice and warm home over there with generous amounts of tlc. Would you be interested in moving secretary to cli-commons?

seems like a great idea! i notice there are no other repos there, though. is it not in use yet?

**Comment by slipset** [comment]
@gf3, it is not in use yet no. We're starting just starting up. But I've been keen on getting something like this going for a while. Personally I'm motivated to keep `clj-commons` running for some time, but my ultimate goal would be for it to be something owned by the Clojure community and not reliant on one single person.

**Comment by slipset** [comment]
@gf3 Since I haven't heard from you, I've taken the liberty to fork @wagjo's version of secretary to http://github.com/clj-commons/secretary. I understand that GitHub has functionality to transfer issues, and I'd be more than happy to take over the issues if you wish.

**Comment by kaosko** [comment]
Thanks @borkdude and @slipset, virtual beers on me! Totally saved my bacon with clj-commons/secretary as I upgraded to clojure 1.9, then cljs, then dependencies etc. until everything else was working but the secretary.

**Comment by borkdude** [comment]
@gf3 +1 on transferring issues, stars, PRs and whatnot. It gives clj-commons/secretary a bit more status

**Comment by gf3** [comment]
hi all, it looks like to transfer ownership i'd need access to the `clj-commons` organization:

<img width="775" alt="screen shot 2018-11-13 at 12 53 31 pm" src="https://user-images.githubusercontent.com/18397/48432747-47e7d180-e743-11e8-929a-01fa5667d258.png">

**Comment by slipset** [comment]
Hi @gf3, I've added you as an admin to clj-commons, so you should be able to transfer secretary.
I've also renamed our version of secretary to secretary-forked, so you should be able to transfer it with out problems.

I'll merge the two projects once you've transferred.

Thanks a lot!

Erik.

**Comment by gf3** [comment]
@slipset hey erik, running into some issues. is there somewhere we can chat? i'm available on telegram if that works for you: https://t.me/giannichiappetta

**Comment by slipset** [comment]
Thank you @gf3 Transferring secretary closes this issue :)
