### ISSUE TITLE
Wrong :require keyword usage in README example

### ISSUE THREAD

**Issue by liaowang11** [clj-commons/secretary#98]
According to [When do I use :require vs :import?](http://clojurescriptmadeeasy.com/blog/when-do-i-use-require-vs-import.html).

`:require` `goog.history.EventType` and accessing the enum like `EventType/NAVIGATE` is not right.

Should indeed do a `:import goog.history.EventType` then access the enum like `EventType.NAVIGATE`.

**Comment by borkdude** [comment]
@liaowang11 PR welcome
