### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by piotr-yuxuan** [clj-commons/secretary#99]
Hi @gf3,

Thanks for this project, it's great and very useful! Just asking, do you still have time to maintain it?

**Comment by noprompt** [comment]
@piotr-yuxuan I can't speak for @gf3 but, as a "maintainer" myself, currently, I simply can't devote time to this project.

**Comment by noprompt** [comment]
@piotr-yuxuan, @gf3  perhaps we should invite interested members of the community to take over and complete patches like #50, etc?

**Comment by noprompt** [comment]
I don't think I can make time to address #50 as I'd like, but I think I could spare some time to dig through the open pull requests as many of them are small and have tests.

**Comment by borkdude** [comment]
@piotr-yuxuan See discussion in #100

**Comment by borkdude** [comment]
Yes, this project is now maintained by clj-commons :-)
